name: ticket-management

services:
  postgres:
    container_name: postgres
    image: postgres:17
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: useradmin
      POSTGRES_PASSWORD: abc12345
      POSTGRES_DB: ticketdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: